pub fn all_ship(len: usize) -> indexmap::IndexMap<String, Vec<String>> {
    indexmap::IndexMap::from([
        (String::from("TIE Echelon"), vec!["".to_string(); len]),
        (String::from("Raven's Claw"), vec!["".to_string(); len]),
        (String::from("Malevolence"), vec!["".to_string(); len]),
        (
            String::from("First Order SF TIE Fighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Han's Millennium Falcon"),
            vec!["".to_string(); len],
        ),
        (String::from("Scimitar"), vec!["".to_string(); len]),
        (String::from("Rex's ARC-170"), vec!["".to_string(); len]),
        (
            String::from("First Order TIE Fighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Rey's Millennium Falcon"),
            vec!["".to_string(); len],
        ),
        (String::from("Sith Fighter"), vec!["".to_string(); len]),
        (String::from("Resistance X-wing"), vec!["".to_string(); len]),
        (
            String::from("Anakin's Eta-2 Starfighter"),
            vec!["".to_string(); len],
        ),
        (String::from("Raddus"), vec!["".to_string(); len]),
        (String::from("Hound's Tooth"), vec!["".to_string(); len]),
        (String::from("IG-2000"), vec!["".to_string(); len]),
        (String::from("Xanadu Blood"), vec!["".to_string(); len]),
        (String::from("Ghost"), vec!["".to_string(); len]),
        (
            String::from("Imperial TIE Bomber"),
            vec!["".to_string(); len],
        ),
        (String::from("Slave I"), vec!["".to_string(); len]),
        (String::from("TIE Advanced x1"), vec!["".to_string(); len]),
        (
            String::from("Lando's Millennium Falcon"),
            vec!["".to_string(); len],
        ),
        (String::from("Ebon Hawk"), vec!["".to_string(); len]),
        (
            String::from("Plo Koon's Jedi Starfighter"),
            vec!["".to_string(); len],
        ),
        (String::from("Razor Crest"), vec!["".to_string(); len]),
        (
            String::from("MG-100 StarFortress SF-17"),
            vec!["".to_string(); len],
        ),
        (String::from("Scythe"), vec!["".to_string(); len]),
        (String::from("Vulture Droid"), vec!["".to_string(); len]),
        (String::from("Cassian's U-wing"), vec!["".to_string(); len]),
        (String::from("Seventh Sister"), vec!["".to_string(); len]),
        (String::from("Outrider"), vec!["".to_string(); len]),
        (
            String::from("Umbaran Starfighter"),
            vec!["".to_string(); len],
        ),
        (String::from("Executor"), vec!["".to_string(); len]),
        (String::from("Bistan's U-wing"), vec!["".to_string(); len]),
        (String::from("Emperor's Shuttle"), vec!["".to_string(); len]),
        (String::from("Home One"), vec!["".to_string(); len]),
        (String::from("TIE Silencer"), vec!["".to_string(); len]),
        (
            String::from("BTL-B Y-wing Starfighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Biggs Darklighter's X-wing"),
            vec!["".to_string(); len],
        ),
        (String::from("Executrix"), vec!["".to_string(); len]),
        (
            String::from("Wedge Antilles's X-wing"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Ahsoka Tano's Jedi Starfighter"),
            vec!["".to_string(); len],
        ),
        (String::from("Negotiator"), vec!["".to_string(); len]),
        (
            String::from("Imperial TIE Fighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Clone Sergeant's ARC-170"),
            vec!["".to_string(); len],
        ),
        (String::from("Endurance"), vec!["".to_string(); len]),
        (
            String::from("TIE/IN Interceptor Prototype"),
            vec!["".to_string(); len],
        ),
        (String::from("Chimaera"), vec!["".to_string(); len]),
        (
            String::from("Kylo Ren's Command Shuttle"),
            vec!["".to_string(); len],
        ),
        (String::from("Phantom II"), vec!["".to_string(); len]),
        (
            String::from("Geonosian Soldier's Starfighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Sun Fac's Geonosian Starfighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Geonosian Spy's Starfighter"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Poe Dameron's X-wing"),
            vec!["".to_string(); len],
        ),
        (
            String::from("B-28 Extinction-class Bomber"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Gauntlet Starfighter"),
            vec!["".to_string(); len],
        ),
        (String::from("Finalizer"), vec!["".to_string(); len]),
        (String::from("TIE Reaper"), vec!["".to_string(); len]),
        (String::from("Hyena Bomber"), vec!["".to_string(); len]),
        (
            String::from("Jedi Consular's Starfighter"),
            vec!["".to_string(); len],
        ),
        (String::from("Rebel Y-wing"), vec!["".to_string(); len]),
        (String::from("Profundity"), vec!["".to_string(); len]),
        (String::from("TIE Defender"), vec!["".to_string(); len]),
    ])
}

pub fn all_unit(len: usize) -> indexmap::IndexMap<String, Vec<String>> {
    indexmap::IndexMap::from([
        (
            String::from("Jedi Master Kenobi"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Jedi Master Luke Skywalker"),
            vec!["".to_string(); len],
        ),
        (String::from("Lord Vader"), vec!["".to_string(); len]),
        (String::from("Rey"), vec!["".to_string(); len]),
        (
            String::from("Sith Eternal Emperor"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Supreme Leader Kylo Ren"),
            vec!["".to_string(); len],
        ),
        (String::from("Jabba the Hutt"), vec!["".to_string(); len]),
        (String::from("General Skywalker"), vec!["".to_string(); len]),
        (
            String::from("Commander Luke Skywalker"),
            vec!["".to_string(); len],
        ),
        (String::from("Darth Revan"), vec!["".to_string(); len]),
        (String::from("Darth Vader"), vec!["".to_string(); len]),
        (String::from("Jedi Knight Revan"), vec!["".to_string(); len]),
        (String::from("Mace Windu"), vec!["".to_string(); len]),
        (
            String::from("Rey (Jedi Training)"),
            vec!["".to_string(); len],
        ),
        (String::from("Grand Inquisitor"), vec!["".to_string(); len]),
        (String::from("Third Sister"), vec!["".to_string(); len]),
        (String::from("Maul"), vec!["".to_string(); len]),
        (String::from("Ben Solo"), vec!["".to_string(); len]),
        (String::from("Doctor Aphra"), vec!["".to_string(); len]),
        (String::from("C-3PO"), vec!["".to_string(); len]),
        (
            String::from("Commander Ahsoka Tano"),
            vec!["".to_string(); len],
        ),
        (String::from("Admiral Trench"), vec!["".to_string(); len]),
        (String::from("Aurra Sing"), vec!["".to_string(); len]),
        (String::from("Bossk"), vec!["".to_string(); len]),
        (
            String::from("Geonosian Brood Alpha"),
            vec!["".to_string(); len],
        ),
        (String::from("Greef Karga"), vec!["".to_string(); len]),
        (String::from("HK-47"), vec!["".to_string(); len]),
        (String::from("Jango Fett"), vec!["".to_string(); len]),
        (String::from("Ninth Sister"), vec!["".to_string(); len]),
        (String::from("Seventh Sister"), vec!["".to_string(); len]),
        (String::from("50R-T"), vec!["".to_string(); len]),
        (String::from("Admiral Piett"), vec!["".to_string(); len]),
        (String::from("Asajj Ventress"), vec!["".to_string(); len]),
        (String::from("BB-8"), vec!["".to_string(); len]),
        (String::from("Chewbacca"), vec!["".to_string(); len]),
        (String::from("CT-5555 \"Fives\""), vec!["".to_string(); len]),
        (String::from("Darth Malak"), vec!["".to_string(); len]),
        (String::from("Darth Nihilus"), vec!["".to_string(); len]),
        (String::from("Darth Traya"), vec!["".to_string(); len]),
        (String::from("Embo"), vec!["".to_string(); len]),
        (String::from("Emperor Palpatine"), vec!["".to_string(); len]),
        (String::from("Fifth Brother"), vec!["".to_string(); len]),
        (String::from("General Grievous"), vec!["".to_string(); len]),
        (
            String::from("Grand Admiral Thrawn"),
            vec!["".to_string(); len],
        ),
        (String::from("Grand Master Yoda"), vec!["".to_string(); len]),
        (String::from("Grand Moff Tarkin"), vec!["".to_string(); len]),
        (String::from("Hermit Yoda"), vec!["".to_string(); len]),
        (String::from("Hondo Ohnaka"), vec!["".to_string(); len]),
        (
            String::from("Jedi Knight Luke Skywalker"),
            vec!["".to_string(); len],
        ),
        (String::from("Jyn Erso"), vec!["".to_string(); len]),
        (
            String::from("Kylo Ren (Unmasked)"),
            vec!["".to_string(); len],
        ),
        (String::from("Moff Gideon"), vec!["".to_string(); len]),
        (String::from("Mon Mothma"), vec!["".to_string(); len]),
        (String::from("Mother Talzin"), vec!["".to_string(); len]),
        (
            String::from("Obi-Wan Kenobi (Old Ben)"),
            vec!["".to_string(); len],
        ),
        (String::from("Padmé Amidala"), vec!["".to_string(); len]),
        (String::from("R2-D2"), vec!["".to_string(); len]),
        (String::from("Shaak Ti"), vec!["".to_string(); len]),
        (String::from("T3-M4"), vec!["".to_string(); len]),
        (String::from("The Mandalorian"), vec!["".to_string(); len]),
        (
            String::from("The Mandalorian (Beskar Armor)"),
            vec!["".to_string(); len],
        ),
        (String::from("Wampa"), vec!["".to_string(); len]),
        (String::from("Zorii Bliss"), vec!["".to_string(); len]),
        (String::from("Admiral Raddus"), vec!["".to_string(); len]),
        (String::from("Darth Malgus"), vec!["".to_string(); len]),
        (String::from("Starkiller"), vec!["".to_string(); len]),
        (
            String::from("Luke Skywalker (Farmboy)"),
            vec!["".to_string(); len],
        ),
        (String::from("Omega"), vec!["".to_string(); len]),
        (
            String::from("Mara Jade, The Emperor's Hand"),
            vec!["".to_string(); len],
        ),
        (String::from("Bastila Shan"), vec!["".to_string(); len]),
        (
            String::from("Bastila Shan (Fallen)"),
            vec!["".to_string(); len],
        ),
        (String::from("Boba Fett"), vec!["".to_string(); len]),
        (String::from("Dengar"), vec!["".to_string(); len]),
        (String::from("Krrsantan"), vec!["".to_string(); len]),
        (String::from("Zam Wesell"), vec!["".to_string(); len]),
        (
            String::from("Boushh (Leia Organa)"),
            vec!["".to_string(); len],
        ),
        (String::from("Eighth Brother"), vec!["".to_string(); len]),
        (String::from("Greedo"), vec!["".to_string(); len]),
        (String::from("Second Sister"), vec!["".to_string(); len]),
        (
            String::from("Boba Fett, Scion of Jango"),
            vec!["".to_string(); len],
        ),
        (String::from("Count Dooku"), vec!["".to_string(); len]),
        (String::from("CT-7567 \"Rex\""), vec!["".to_string(); len]),
        (String::from("Darth Sion"), vec!["".to_string(); len]),
        (String::from("Dash Rendar"), vec!["".to_string(); len]),
        (String::from("Fennec Shand"), vec!["".to_string(); len]),
        (String::from("General Hux"), vec!["".to_string(); len]),
        (String::from("IG-88"), vec!["".to_string(); len]),
        (String::from("Jolee Bindo"), vec!["".to_string(); len]),
        (String::from("Ki-Adi-Mundi"), vec!["".to_string(); len]),
        (String::from("Nute Gunray"), vec!["".to_string(); len]),
        (String::from("Qi'ra"), vec!["".to_string(); len]),
        (String::from("Sana Starros"), vec!["".to_string(); len]),
        (String::from("The Armorer"), vec!["".to_string(); len]),
        (String::from("Darth Talon"), vec!["".to_string(); len]),
        (String::from("Director Krennic"), vec!["".to_string(); len]),
        (String::from("General Kenobi"), vec!["".to_string(); len]),
        (String::from("Iden Versio"), vec!["".to_string(); len]),
        (String::from("Ahsoka Tano"), vec!["".to_string(); len]),
        (
            String::from("Ahsoka Tano (Fulcrum)"),
            vec!["".to_string(); len],
        ),
        (String::from("Amilyn Holdo"), vec!["".to_string(); len]),
        (String::from("B1 Battle Droid"), vec!["".to_string(); len]),
        (
            String::from("B2 Super Battle Droid"),
            vec!["".to_string(); len],
        ),
        (String::from("Barriss Offee"), vec!["".to_string(); len]),
        (String::from("Bo-Katan Kryze"), vec!["".to_string(); len]),
        (String::from("Bodhi Rook"), vec!["".to_string(); len]),
        (String::from("BT-1"), vec!["".to_string(); len]),
        (String::from("Canderous Ordo"), vec!["".to_string(); len]),
        (String::from("Captain Han Solo"), vec!["".to_string(); len]),
        (String::from("Captain Phasma"), vec!["".to_string(); len]),
        (String::from("Cara Dune"), vec!["".to_string(); len]),
        (String::from("Carth Onasi"), vec!["".to_string(); len]),
        (String::from("Cassian Andor"), vec!["".to_string(); len]),
        (String::from("CC-2224 \"Cody\""), vec!["".to_string(); len]),
        (String::from("Chief Chirpa"), vec!["".to_string(); len]),
        (
            String::from("Clone Wars Chewbacca"),
            vec!["".to_string(); len],
        ),
        (String::from("Colonel Starck"), vec!["".to_string(); len]),
        (
            String::from("CT-21-0408 \"Echo\""),
            vec!["".to_string(); len],
        ),
        (String::from("Dark Trooper"), vec!["".to_string(); len]),
        (String::from("Darth Maul"), vec!["".to_string(); len]),
        (String::from("Darth Sidious"), vec!["".to_string(); len]),
        (String::from("Death Trooper"), vec!["".to_string(); len]),
        (String::from("Droideka"), vec!["".to_string(); len]),
        (String::from("Echo"), vec!["".to_string(); len]),
        (String::from("Enfys Nest"), vec!["".to_string(); len]),
        (String::from("Ezra Bridger"), vec!["".to_string(); len]),
        (String::from("Finn"), vec!["".to_string(); len]),
        (String::from("Gamorrean Guard"), vec!["".to_string(); len]),
        (String::from("Gar Saxon"), vec!["".to_string(); len]),
        (
            String::from("Garazeb \"Zeb\" Orrelios"),
            vec!["".to_string(); len],
        ),
        (String::from("General Veers"), vec!["".to_string(); len]),
        (String::from("Han Solo"), vec!["".to_string(); len]),
        (String::from("Hera Syndulla"), vec!["".to_string(); len]),
        (String::from("Hunter"), vec!["".to_string(); len]),
        (String::from("IG-100 MagnaGuard"), vec!["".to_string(); len]),
        (String::from("IG-11"), vec!["".to_string(); len]),
        (
            String::from("Imperial Probe Droid"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Jedi Knight Anakin"),
            vec!["".to_string(); len],
        ),
        (String::from("Juhani"), vec!["".to_string(); len]),
        (String::from("K-2SO"), vec!["".to_string(); len]),
        (String::from("Kanan Jarrus"), vec!["".to_string(); len]),
        (String::from("Kuiil"), vec!["".to_string(); len]),
        (String::from("Kylo Ren"), vec!["".to_string(); len]),
        (String::from("L3-37"), vec!["".to_string(); len]),
        (String::from("Logray"), vec!["".to_string(); len]),
        (String::from("Luminara Unduli"), vec!["".to_string(); len]),
        (String::from("Mission Vao"), vec!["".to_string(); len]),
        (
            String::from("Nightsister Initiate"),
            vec!["".to_string(); len],
        ),
        (String::from("Old Daka"), vec!["".to_string(); len]),
        (String::from("Pao"), vec!["".to_string(); len]),
        (String::from("Paploo"), vec!["".to_string(); len]),
        (String::from("Princess Leia"), vec!["".to_string(); len]),
        (String::from("Qui-Gon Jinn"), vec!["".to_string(); len]),
        (
            String::from("Rebel Officer Leia Organa"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Resistance Hero Finn"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Resistance Hero Poe"),
            vec!["".to_string(); len],
        ),
        (String::from("Rey (Scavenger)"), vec!["".to_string(); len]),
        (String::from("Rose Tico"), vec!["".to_string(); len]),
        (String::from("Sabine Wren"), vec!["".to_string(); len]),
        (String::from("Savage Opress"), vec!["".to_string(); len]),
        (String::from("Sith Trooper"), vec!["".to_string(); len]),
        (String::from("Tech"), vec!["".to_string(); len]),
        (String::from("Threepio & Chewie"), vec!["".to_string(); len]),
        (String::from("Vandor Chewbacca"), vec!["".to_string(); len]),
        (
            String::from("Veteran Smuggler Chewbacca"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Veteran Smuggler Han Solo"),
            vec!["".to_string(); len],
        ),
        (String::from("Visas Marr"), vec!["".to_string(); len]),
        (String::from("Wat Tambor"), vec!["".to_string(); len]),
        (String::from("Wicket"), vec!["".to_string(); len]),
        (String::from("Wrecker"), vec!["".to_string(); len]),
        (String::from("Young Han Solo"), vec!["".to_string(); len]),
        (
            String::from("Young Lando Calrissian"),
            vec!["".to_string(); len],
        ),
        (String::from("Zaalbar"), vec!["".to_string(); len]),
        (String::from("0-0-0"), vec!["".to_string(); len]),
        (String::from("Kyle Katarn"), vec!["".to_string(); len]),
        (
            String::from("Skiff Guard (Lando Calrissian)"),
            vec!["".to_string(); len],
        ),
        (String::from("Stormtrooper Han"), vec!["".to_string(); len]),
        (String::from("ARC Trooper"), vec!["".to_string(); len]),
        (
            String::from("First Order Stormtrooper"),
            vec!["".to_string(); len],
        ),
        (
            String::from("First Order TIE Pilot"),
            vec!["".to_string(); len],
        ),
        (String::from("Royal Guard"), vec!["".to_string(); len]),
        (String::from("Stormtrooper"), vec!["".to_string(); len]),
        (String::from("Tusken Raider"), vec!["".to_string(); len]),
        (String::from("Cad Bane"), vec!["".to_string(); len]),
        (String::from("Baze Malbus"), vec!["".to_string(); len]),
        (String::from("Chirrut Îmwe"), vec!["".to_string(); len]),
        (String::from("Chopper"), vec!["".to_string(); len]),
        (String::from("Geonosian Spy"), vec!["".to_string(); len]),
        (
            String::from("Nightsister Zombie"),
            vec!["".to_string(); len],
        ),
        (String::from("Poggle the Lesser"), vec!["".to_string(); len]),
        (String::from("Sun Fac"), vec!["".to_string(); len]),
        (String::from("Teebo"), vec!["".to_string(); len]),
        (String::from("Aayla Secura"), vec!["".to_string(); len]),
        (String::from("Admiral Ackbar"), vec!["".to_string(); len]),
        (String::from("Bistan"), vec!["".to_string(); len]),
        (String::from("Chief Nebit"), vec!["".to_string(); len]),
        (String::from("Dathcha"), vec!["".to_string(); len]),
        (String::from("Eeth Koth"), vec!["".to_string(); len]),
        (String::from("Ima-Gun Di"), vec!["".to_string(); len]),
        (String::from("Jawa Engineer"), vec!["".to_string(); len]),
        (String::from("Jawa Scavenger"), vec!["".to_string(); len]),
        (String::from("Kit Fisto"), vec!["".to_string(); len]),
        (String::from("Lobot"), vec!["".to_string(); len]),
        (String::from("Plo Koon"), vec!["".to_string(); len]),
        (String::from("Poe Dameron"), vec!["".to_string(); len]),
        (String::from("Talia"), vec!["".to_string(); len]),
        (String::from("URoRRuR'R'R"), vec!["".to_string(); len]),
        (String::from("Wedge Antilles"), vec!["".to_string(); len]),
        (String::from("Lando Calrissian"), vec!["".to_string(); len]),
        (String::from("Biggs Darklighter"), vec!["".to_string(); len]),
        (
            String::from("Clone Sergeant - Phase I"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Coruscant Underworld Police"),
            vec!["".to_string(); len],
        ),
        (String::from("Ewok Elder"), vec!["".to_string(); len]),
        (String::from("Ewok Scout"), vec!["".to_string(); len]),
        (
            String::from("First Order Executioner"),
            vec!["".to_string(); len],
        ),
        (
            String::from("First Order Officer"),
            vec!["".to_string(); len],
        ),
        (
            String::from("First Order SF TIE Pilot"),
            vec!["".to_string(); len],
        ),
        (String::from("Geonosian Soldier"), vec!["".to_string(); len]),
        (String::from("Hoth Rebel Scout"), vec!["".to_string(); len]),
        (
            String::from("Hoth Rebel Soldier"),
            vec!["".to_string(); len],
        ),
        (
            String::from("IG-86 Sentinel Droid"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Imperial Super Commando"),
            vec!["".to_string(); len],
        ),
        (String::from("Jawa"), vec!["".to_string(); len]),
        (String::from("Jedi Consular"), vec!["".to_string(); len]),
        (
            String::from("Jedi Knight Guardian"),
            vec!["".to_string(); len],
        ),
        (String::from("Magmatrooper"), vec!["".to_string(); len]),
        (String::from("Mob Enforcer"), vec!["".to_string(); len]),
        (
            String::from("Nightsister Acolyte"),
            vec!["".to_string(); len],
        ),
        (
            String::from("Nightsister Spirit"),
            vec!["".to_string(); len],
        ),
        (String::from("Range Trooper"), vec!["".to_string(); len]),
        (
            String::from("Scarif Rebel Pathfinder"),
            vec!["".to_string(); len],
        ),
        (String::from("Shoretrooper"), vec!["".to_string(); len]),
        (String::from("Sith Assassin"), vec!["".to_string(); len]),
        (
            String::from("Sith Empire Trooper"),
            vec!["".to_string(); len],
        ),
        (String::from("Sith Marauder"), vec!["".to_string(); len]),
        (String::from("Snowtrooper"), vec!["".to_string(); len]),
        (String::from("TIE Fighter Pilot"), vec!["".to_string(); len]),
        (String::from("Tusken Shaman"), vec!["".to_string(); len]),
        (String::from("Resistance Pilot"), vec!["".to_string(); len]),
        (
            String::from("Resistance Trooper"),
            vec!["".to_string(); len],
        ),
        (String::from("Ugnaught"), vec!["".to_string(); len]),
    ])
}
